# Generated by Django 4.2.5 on 2023-09-25 19:54

from django.db import migrations, models
import social_media.models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to=social_media.models.post_image_file_path,
            ),
        ),
    ]
